[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python supportbot.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Include webapp-support-bot directory in deployment
[deploy.include]
paths = ["webapp-support-bot/**"]
